apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: thanhdhnt/multi-apik8s:v1.0.0
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_ADDR
              value: redis-cluster-ip-service:6379
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: fibonacci
            - name: POSTGRES_HOST
              value: postgres-cluster-ip-service
            - name: DB_SOURCE
              value: postgresql://root:secret@postgres-cluster-ip-service:5432/fibonacci?sslmode=disable

    