// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Fib struct {
	ID       int64     `json:"id"`
	Index    int64     `json:"index"`
	Value    int64     `json:"value"`
	CreateAt time.Time `json:"create_at"`
}
