// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateFibonacci(ctx context.Context, arg CreateFibonacciParams) (Fib, error)
	DeleteFibonacci(ctx context.Context, id int64) error
	GetFibonacciByID(ctx context.Context, id int64) (Fib, error)
	GetFibonacciByIndex(ctx context.Context, index int64) (Fib, error)
	GetLatestCreatedFibonacci(ctx context.Context) (Fib, error)
	ListFibonaccis(ctx context.Context, limit int32) ([]Fib, error)
}

var _ Querier = (*Queries)(nil)
